name: Check Style Code

on:
  push:
    branches:
      - new_branch2
  pull_request:
    branches:
      - new_branch2

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v2

      - name: Set version python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install flake8

      - name: Run linter
        run: |
          flake8 .